language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
install:
  - pip3 install -r requirements.txt
  - python3 manage.py makemigrations events
  - python3 manage.py makemigrations orgs
  - python3 manage.py makemigrations sharing_groups
  - python3 manage.py makemigrations sync
  - python3 manage.py migrate
script: python3 manage.py test
